"""Bake the tile characters into SVG paths, so every device draws the same
brush lettering without downloading a font.

The source is LXGW WenKai (SIL Open Font License), which is not committed.
To regenerate after changing GLYPHS:

    pip install fonttools
    curl -LO https://github.com/lxgw/LxgwWenKai/releases/download/v1.522/LXGWWenKai-Medium.ttf
    python pipeline/bake_glyphs.py LXGWWenKai-Medium.ttf

Paths are written y-down in a 1000-unit em square (top of the em at 0), so a
glyph drawn at size s centred on (x, y) is translate(x - s/2, y - s/2)
scale(s / 1000).
"""

import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

GLYPHS = "一二三四伍六七八九萬東南西北中發春夏秋冬梅蘭菊竹"
OUT = Path(__file__).resolve().parent.parent / "src/components/glyphs.ts"


def bake(font_path: str) -> str:
    font = TTFont(font_path)
    assert font["head"].unitsPerEm == 1000
    top = font["OS/2"].sTypoAscender
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    lines = []
    for char in GLYPHS:
        pen = SVGPathPen(glyphs, ntos=lambda n: f"{n:g}")
        # Flip y and move the em top to 0.
        glyphs[cmap[ord(char)]].draw(TransformPen(pen, (1, 0, 0, -1, 0, top)))
        lines.append(f'  {char}: "{pen.getCommands()}",')
    return (
        "// Generated by pipeline/bake_glyphs.py from LXGW WenKai (SIL OFL).\n"
        "// Do not edit by hand.\n\n"
        "export const GLYPHS: Record<string, string> = {\n"
        + "\n".join(lines)
        + "\n};\n"
    )


if __name__ == "__main__":
    OUT.write_text(bake(sys.argv[1]), encoding="utf-8")
    print(f"wrote {OUT}")
